### ISSUE TITLE
Carriage return problem...

### ISSUE THREAD

**Issue by tkuhn** [trustyuri/trustyuri-java#3]
There seems to be a problem when RDF literals contain carriage return characters (\r). I think the problem is that Sesame simply drops them, but I need to investigate...

**Comment by tkuhn** [comment]
I finally found time to look into this. I looks to me as if Sesame replaces carriage return characters by new lines. I read a TriG file containing carriage returns, and on the Java side I only see them as new lines... I guess I should report this as a Sesame bug.

**Comment by ansell** [comment]
If it is different to SES-425, then report it and reference it, otherwise we would gladly accept a patch to make the XML SAX Parser do the right thing.

We recently patched the Turtle parser that had a similar issue, but it is only fixed in 2.8.0, and not in the 2.7.x series yet (I haven't had time to backport the patch yet):

https://bitbucket.org/openrdf/sesame/pull-request/359/ses-1712-fixed-newline-problem-by-getting/diff

**Comment by ansell** [comment]
Come to think of it, the TriG parser piggybacks on the Turtle parser, so it should be fixed for TriG in 2.8.0 also.

**Comment by tkuhn** [comment]
OK, I should try 2.8.0 then!

Switching to 2.8.0 now lets test suite fail: Apparently, version 2.8.0 automatically assigns all literals the type http://www.w3.org/2001/XMLSchema#string if they don't have any type attached in the source file. This was different in version 2.7.12, where literals could be plain literals. Is there a way to suppress this behavior?

**Comment by ansell** [comment]
Not really, that is a direct consequence of the new RDF-1.1 specification. You can only supress it for serialisation, not in-memory, and it should be supressed for Turtle/TriG by default.

**Comment by ansell** [comment]
The fixes should be in 2.7.15 when it is released if you can wait until then, btw.

**Comment by tkuhn** [comment]
Oh no. That means the current implementation (and many generated trusty URIs) are not RDF 1.1 compliant...

**Comment by tkuhn** [comment]
This has become a new issue (and a big one at that): #4

**Comment by tkuhn** [comment]
At least I can confirm that this bug is fixed after switching to 2.8.0.

**Comment by tkuhn** [comment]
Fixed in c06facd873a7da51905aef69d1e536181d347b6e
