### ISSUE TITLE
Plain literals

### ISSUE THREAD

**Issue by tkuhn** [trustyuri/trustyuri-java#4]
Treating plain literals differently from string-typed literals is inconsistent with the RDF 1.1 specification. See #3.

The trusty URI specification has to be rewritten and existing trusty URIs (type R) have to be recalculated, before we can release Version 1 of the specification.

**Comment by ansell** [comment]
The other RDF-1.1 consequence is that language literals always have a datatype internally, rdf:langString, so you need to check for language before checking for datatype, or do the check across both at the same time.

**Comment by tkuhn** [comment]
I think the language literals should be OK. If there is a language tag then the datatype is always `http://www.w3.org/1999/02/22-rdf-syntax-ns#langString` (if I am not mistaken). So, I think the algorithm should go like that: if there is a language tag, the language tag string goes into the hash; otherwise the datatype URI goes into the hash. No need to hash the datatype in the first case, as it is always exactly the same. Does that sound right?

**Comment by ansell** [comment]
It sounds right, you will just have to double check (or have automatic testing) that two literals with the same lexical value and different language tags generate different hashes.

**Comment by tkuhn** [comment]
OK, thanks for your help.

For the record, this is the relevant part of the RDF 1.1 specification: http://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal

**Comment by tkuhn** [comment]
Solved in all the trusty URI implementations.

I still need to figure out a migration plan for existing trusty URIs and for the nanopub server network. And the testsuite needs to be extended too.

So, I keep this issue open for the time being.
